version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: self‑hosted-pyannote-diarization:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    env_file:
      - .env

    # For Compose / Docker versions that support GPU reservations
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all       # or use a number like 1
              capabilities: [gpu]

    # Fallback / older approach (if device_requests is unsupported)
    runtime: nvidia
      
